services:
  grafana-export-to-pdf:
    build: .
    container_name: grafana-export-to-pdf
    ports:
      - "${EXPORT_SERVER_PORT:-3001}:${EXPORT_SERVER_PORT:-3001}"
    network_mode: "host"
    volumes:
      - ./output:/usr/src/app/output
      - ./debug:/usr/src/app/debug
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - EXPORT_SERVER_PORT=${EXPORT_SERVER_PORT:-3001}
      - XDG_CONFIG_HOME=/tmp/.chromium
      - XDG_CACHE_HOME=/tmp/.chromium
